name: Publish version image
on:
  release:
    types:
      - created

env:
  # DOCKERPLATFORM: "linux/amd64,linux/arm64"
  DOCKERPLATFORM: "linux/amd64,linux/arm64,linux/s390x"
  DOCKERIMAGE: "ghcr.io/ofvp-project/openssh"

jobs:
  latestDeploy:
    runs-on: ubuntu-latest
    name: Publish version
    environment:
      name: Docker_Version
      url: "ghcr.io/ofvp-project/wireguard"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup QEMU to Docker
        uses: docker/setup-qemu-action@v1

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login into registry Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Get package version"
        run: echo "PACKAGE_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV

      - name: Build and Push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          target: server
          tags: ${{ env.DOCKERIMAGE }}:${{ env.PACKAGE_VERSION }}
          platforms: ${{ env.DOCKERPLATFORM }}
          cache-from: type=gha,scope=${{ github.ref }}_${{ hashFiles('**/package-lock.json') }}
          cache-to: type=gha,mode=max,scope=${{ github.ref }}_${{ hashFiles('**/package-lock.json') }}
